twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['tailwind_2_layout.html.twig']
    paths:
        'templates/email/': 'email'
        '%kernel.project_dir%/assets/images': images

when@test:
    twig:
        strict_variables: true
