framework:
    workflows:
        meeting:
            type: state_machine
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Meeting
            initial_marking: draft
            places:
                - draft
                - pending
                - confirmed
                - started
                - ended
                - wait_for_recording
                - playable
                - canceled
            transitions:
                request:
                    from: draft
                    to: pending
                confirm:
                    from: pending
                    to: confirmed
                auto_validate:
                    from: draft
                    to: confirmed
                    metadata:
                        manual_action: false
                start:
                    guard: "subject.isJoinable()"
                    from: confirmed
                    to:   started
                end:
                    from: started
                    to:   ended
                    metadata:
                        manual_action: false
                wait_for_recording:
                    from: started
                    to:   wait_for_recording
                    metadata:
                        manual_action: false
                to_playable:
                    from: ended
                    to:   playable
                    metadata:
                        manual_action: false
                cancel:
                    from: pending
                    to:   canceled

when@dev:
    framework:
        workflows:
            meeting:
                audit_trail:
                    enabled: true
