framework:
    workflows:
        meeting:
            type: state_machine
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Meeting
            initial_marking: draft
            places:
                - draft
                - pending
                - started
                - ended
                - canceled
            transitions:
                request:
                    from: draft
                    to: pending
                start:
                    from: pending
                    to:   started
                end:
                    from: started
                    to:   ended
                cancel:
                    from: pending
                    to:   canceled

when@dev:
    framework:
        workflows:
            meeting:
                audit_trail:
                    enabled: true
