name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
      with:
        php_extensions: zip xsl intl pdo_pgsql
    - uses: php-actions/phpstan@v3
      with:
        path: src/
        php_version: 8.1
        error_format: github
        configuration: phpstan.neon
